# SwiftLint Configuration for Afterflow

included:
  - Afterflow

excluded:
  - Pods
  - .build
  - DerivedData

# Opt-in rules
opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - empty_count
  - explicit_init
  - fatal_error_message
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Disabled rules (SwiftFormat handles these)
disabled_rules:
  - trailing_comma # SwiftFormat handles this
  - vertical_whitespace # SwiftFormat handles this
  - opening_brace # SwiftFormat handles this
  - closing_brace # SwiftFormat handles this
  - colon # SwiftFormat handles this
  - comma # SwiftFormat handles this
  - function_name_whitespace # SwiftFormat handles this (renamed from operator_whitespace)

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - db
    - to
    - at
    - on
    - in
    - up
    - i  # Loop counters
    - x  # Coordinates
    - y  # Coordinates

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 5

# Custom reporter
reporter: "xcode"
